language: node
sudo: false
cache:
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
before_install:
  - nvm install 6
  - npm install -g codecov
install:
  - npm install
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    export CHROME_BIN=chromium-browser
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
script:
  - npm run build
  - npm test
after_success:
  - codecov
