# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  nodejs_version: "8.12"

# build cache to preserve files/folders between builds
cache:
  - '%AppData%/npm-cache'

# scripts that run after cloning repository
install:
  # Install node:
  - ps: Install-Product node $env:nodejs_version
  # Install dependencies:
  - 'npm install'

build: off

# to run your custom scripts instead of automatic tests
test_script:
  - 'npm run build'
  - 'npm test'

on_success:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - codecov -X gcov --file "%APPVEYOR_BUILD_FOLDER%\coverage.xml"
