name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        node --version

        npm install

    - name: Build
      run: |
        npm run build

    - name: Run tests
      run: |
        npm run test:ci

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
